server:
  port: 8093
spring:
  application:
    name: wei-eureka-server
eureka:
  instance:
    hostname: peer3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8091/eureka/, http://peer2:8092/eureka/